micronaut:
  application:
    name: conversations
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
kafka.bootstrap.servers: localhost:9092
jpa.default.properties.hibernate.hbm2ddl.auto: update
