micronaut:
  server:
    port: 6060
  application:
    name: authenticator
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:salesboxArchictectureSecretForDevelopment}"'
