micronaut:
  server:
    port: 6160
  application:
    name: bizObjects
  router:
    static-resources:
      steps:
        paths: classpath:steps
        mapping: /steps/**
      events:
        paths: classpath:steps
        mapping: /events/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:salesboxArchictectureSecretForDevelopment}"'
datasources:
  default:
    url: jdbc:mysql://localhost:3306/v6_biz
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages: 'biz.objects.db'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
