micronaut:
  server:
    port: 6260
  application:
    name: leadScoring
datasources:
  default:
    url: jdbc:mysql://localhost:3306/v6_scoring
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages: 'lead.scoring.db'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
