micronaut:
  server:
    port: 6560
  application:
    name: eventServer
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:salesboxArchictectureSecretForDevelopment}"'
kafka.bootstrap.servers: localhost:9092
