micronaut:
  server:
    port: 6360
  application:
    name: activities
datasources:
  default:
    url: jdbc:mysql://localhost:3306/v6_activities
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    dialect: MYSQL
kafka.bootstrap.servers: localhost:9092
jpa.default:
  entity_scan:
    packages: 'activities.db'
  properties:
    hibernate:
      hbm2ddl:
        auto: update
      show_sql: true
